name: Build and Deploy Python Calculator Web Application using Docker

on:
  push:
    branches:
      - python-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Check out the source code from the repository
        with:
          repository: 'movecloud-development/python-calculator'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Docker Image
        run: |
          docker build -t python-calculator-app .
        working-directory: ${{ github.workspace }}

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Save Docker Image as Tarball
        run: |
          docker save -o python-calculator-app.tar python-calculator-app
        working-directory: ${{ github.workspace }}

      - name: Push Docker Image Tarball to S3
        run: |
          aws s3 cp python-calculator-app.tar s3://terraformlab-1/python-calculator-app.tar
        env:
          S3_BUCKET: terraformlab-1

      - name: Copy Docker Image Tarball to EC2 Instance (via SSH)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # Replace with your EC2 instance username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Replace with your EC2 instance SSH private key (base64-encoded)
          source: "${{ github.workspace }}/python-calculator-app.tar"
          target: "/home/python-calculator-app.tar"
          debug: "true"

      - name: Load Docker Image from Tarball and Run (via SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # Replace with your EC2 instance username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Replace with your EC2 instance SSH private key (base64-encoded)
          port: 22
          script: |
            cd /home
            docker load -i python-calculator-app.tar
            docker run -d --name python-calculator-app -p 80:8080 python-calculator-app
